tsparser: better errors when defining secrets (#1461)
Check if secret is defined within a function and gives a error
referencing the secret with a note referencing the function

```
error: secrets must be defined globally
  --> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:36:27
   |
36 |       const githubToken = secret("GitHubAPIToken");
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: secret defined within this function
  --> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:27:3
   |
27 | /   async ({ name }: { name: string }): Promise<Response> => {
28 | |     try {
29 | |       // ..
30 | |       // ..
...  |
41 | |     }
42 | |   },
   | |___^
```

---------

Co-authored-by: André Eriksson <andre@encore.dev>