tsparser: duplicate api name error (#1814)
emit error when two endpoints with the same name are defined within the
same service

```
error: api endpoints with conflicting names defined within the same service
  --> /home/fredr/projects/encore-apps/ts-tags/other/otherfile.ts:3:14
   |
3  | export const get1 = api(
   |              ^^^^
   |
note: previously defined here
  --> /home/fredr/projects/encore-apps/ts-tags/other/other.ts:18:14
   |
18 | export const get1 = api(
   |              ^^^^

```