Ignore TS compile errors for makeRecord function (#771)
Adding a `@ts-ignore` comment before the `makeRecord`-function in the
generated TS client.

I get a Typescript compilation error for this function, I can not build
my project after generating the client. The reason is that we are adding
that function but in my case it is never used, so I get error TS6133:
'makeRecord' is declared but its value is never read.

Another option is to add a `@ts-nocheck` comment at the top of the file
but ignoring everything feels a bit scary, then we run the risk of
introducing runtime errors instead.

---------

Co-authored-by: André Eriksson <andre@encore.dev>